### ISSUE TITLE
Future blocks not appearing on 1.8 clients

### ISSUE THREAD

**Issue by alexmarkey** [ViaVersion/ViaRewind#322] opened 2021-06-09 22:37 UTC
**Describe the bug, provide any errors**
This has started since the 1.17 update (we updated ViaVersion, ViaRewind and ViaBackwards on our servers).
Our server backends are 1.12.
Pretty much if a 1.8 client logs into our 1.12 server, all of the 'Future Blocks' just appear as air (rather than being translated into something visible for that client).

For example this screenshot is taken on a 1.12 client https://gyazo.com/3c609e8716c677cad292841fd2b74ea3
And this screenshot is taken on a 1.8 client https://gyazo.com/1d42eb720137e6991908d12ef4b85169

**How can we reproduce it?**
1. Use server version1.12.2
2. Use the latest ViaVersion, ViaRewind, ViaBackwards (the ones that were just released for the 1.17 updates)
3. Place a 1.12 block (for example Purpur block)
4. Login using 1.8 client (and you will notice it is invisible)

**Expected behaviour**
The blocks should get translated to something that is visible for that client version.

**ViaVersion Dump:**
https://dump.viaversion.com/59f401d2029b9c9a36786b80a8d0745577a0d01a5225ee60bf92adb2573977b9

**Additional server info**
Yes - We use LilyPad

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by creeper123123321** [comment] 2021-06-09 23:31
is it described by #303 ?

**Comment by creeper123123321** [comment] 2021-06-09 23:32
Looks like a dupe of #303

**Closed by creeper123123321** 2021-06-09 23:32 UTC
