### ISSUE TITLE
Players are kicked out after entering the game to generate an error report

### ISSUE THREAD

**Issue by 1983378984** [ViaVersion/ViaRewind#423] opened 2023-01-07 13:37 UTC
### `/viaversion dump` Output

 https://dump.viaversion.com/1cf2cfdf651e73fa8a40a733c0b419e06f50c4cb72ca07cd1f5b63921dc359f7

### Console Error

[ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!
[21:24:45 WARN]: [ViaBackwards] You have min/max set to -64/256
[21:24:45 WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[21:24:45 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[21:24:45 WARN]: Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[21:24:45 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:24:45 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:24:45 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[21:24:45 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[21:24:45 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[21:24:45 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[21:24:45 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[21:24:45 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[21:24:45 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[21:24:45 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[21:24:45 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[21:24:45 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:24:45 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:24:45 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:24:45 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:24:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:24:45 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[21:24:45 WARN]: Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[21:24:45 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(5021) + length(56) exceeds writerIndex(5042): PooledUnsafeDirectByteBuf(ridx: 5021, widx: 5042, cap: 8192)
[21:24:45 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[21:24:45 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
[21:24:45 WARN]:        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:137)
[21:24:45 WARN]:        at ViaBackwards-4.5.2-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3.lambda$registerMap$0(EntityPackets1_19_3.java:132)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:381)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[21:24:45 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:36)
[21:24:45 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:24:45 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:24:45 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[21:24:45 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[21:24:45 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[21:24:45 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[21:24:45 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[21:24:45 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[21:24:45 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[21:24:45 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[21:24:45 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[21:24:45 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[21:24:45 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:24:45 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:24:45 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:24:45 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:24:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:24:45 INFO]: ViggBorder765 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[21:24:45 WARN]: [EliteMobs] Failed to get blob value from database!
[21:24:45 WARN]: [EliteMobs] UUID: 999c6496-322c-3cc4-a86c-cc82912c7360 | Value: PlayerQuestCooldowns
[21:24:45 WARN]: java.sql.SQLException: ResultSet closed
[21:24:45 WARN]:        at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
[21:24:45 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:39)
[21:24:45 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:261)
[21:24:45 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getDatabaseBlob(PlayerData.java:381)
[21:24:45 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getPlayerQuestCooldowns(PlayerData.java:331)
[21:24:45 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.quests.playercooldowns.PlayerQuestCooldowns.flushPlayer(PlayerQuestCooldowns.java:86)
[21:24:45 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.quests.playercooldowns.PlayerQuestCooldownsLogout.onPlayerLogout(PlayerQuestCooldownsLogout.java:10)
[21:24:45 WARN]:        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:40)
[21:24:45 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[21:24:45 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:24:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680)
[21:24:45 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:575)
[21:24:45 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:558)
[21:24:45 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2210)
[21:24:45 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2189)
[21:24:45 WARN]:        at net.minecraft.network.NetworkManager.m(NetworkManager.java:784)
[21:24:45 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:603)
[21:24:45 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:233)
[21:24:45 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1594)
[21:24:45 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:482)
[21:24:45 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[21:24:45 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194)
[21:24:45 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[21:24:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Bug Description

Kick the player out after generating an error report

### Steps to Reproduce

use purpur-1886 1.19.3
Used the plugin in the screenshot
![Q356VK~$TK EYC9UR5{7DSV](https://user-images.githubusercontent.com/62001480/211153450-f3b61fab-aff2-4ad0-8a77-cdd8909919b9.png)
![$KK`SD{FFMGV 1LGF6UROHB](https://user-images.githubusercontent.com/62001480/211153452-f7126cf6-20ac-4900-be39-b03cb52fdd4a.png)
![PT_18LCD UZCJJC4F% $QW](https://user-images.githubusercontent.
![EXSRR 7}Y(G4IR S64{%2%Y](https://user-images.githubuserc
![F(PA437 U`K Y0YHQ%6`569](https://user-images.githubusercontent.com/62001480/211153464-959b4c30-cbf8-4ff5-b5ae-8b763655de32.png)
ontent.com/62001480/211153462-0b21b68a-c332-44b6-b626-e9180985fef6.png)
com/62001480/211153455-fce1700c-69ec-4bbe-b0a3-b3ae5dcaab9f.png)
![DU)2P4PPN%F@9}LJQH29}53](https://user-images.githubusercontent.com/62001480/211153458-8582e675-8544-4a48-8f9a-deb8bccd0baa.png)

### Expected Behavior

Resolving bugs

### Additional Server Info

use velocity
none

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment] 2023-01-07 13:37
![Platform: git--Purpur--1886%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1886%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by 1983378984** [comment] 2023-01-07 13:37
![$KK`SD{FFMGV 1LGF6UROHB](https://user-images.githubusercontent.com/62001480/211153529-1fd88ce0-03f7-4a48-a212-153d1aecb6fa.png)
![PT_18LCD UZCJJC4F% $QW](https://user-images.githubusercontent.com/62001480/211153530-6476d9f3-c0f5-4a2f-957d-6a8152feee09.png)
![DU)2P4PPN%F@9}LJQH29}53](https://user-images.githubusercontent.com/62001480/211153532-826f7df7-b990-4d2b-b7a5-34e49759b57a.png)
![EXSRR 7}Y(G4IR S64{%2%Y](https://user-images.githubusercontent.com/62001480/211153534-c3f526e8-8bc9-457f-a6d3-5135ce4ac3b3.png)
![F(PA437 U`K Y0YHQ%6`569](https://user-images.githubusercontent.com/62001480/211153536-53b4c291-780f-46a6-a072-88e7211839a2.png)
![Q356VK~$TK EYC9UR5{7DSV](https://user-images.githubusercontent.com/62001480/211153537-94c9809e-2537-4b86-8fe1-1bf089b9811b.png)

**Comment by kennytv** [comment] 2023-01-07 13:39
Duplicate of your own issue (https://github.com/ViaVersion/ViaRewind/issues/423)

**Closed by kennytv** 2023-01-07 13:39 UTC
Labels: Unconfirmed
