### ISSUE TITLE
Bow charging animation is not visible on other players with 1.8.9 client

### ISSUE THREAD

**Issue by ghost** [ViaVersion/ViaRewind#64] opened 2018-02-14 07:31 UTC
Title explains it all I think ^
using PaperSpigot 1.11.2

**Comment by SaltyPotata** [comment] 2020-05-13 20:54
I got my issues page closed? Why?

**Comment by KennyTV** [comment] 2020-05-13 21:29
Because it's a duplicate of... this 👀

**Comment by SaltyPotata** [comment] 2020-05-13 21:30
> Because it's a duplicate of... this 👀

Yea but can it get fixed? This was posted in 2018 ???

**Comment by Govindass** [comment] 2020-05-14 12:30
yup a fix would be nice, I'm still waiting for it since 2018

**Comment by instaaftereffects** [comment] 2021-02-19 18:43
Any update on a fix for this?

**Comment by zannapzg** [comment] 2021-06-03 07:29
Hi, news about this?

**Comment by Redblock6YT** [comment] 2021-07-26 23:50
I also have this problem? Any updates? I'm developing a One In The Quiver server and it's crucial to be able to see bow charging animation.

Thanks.

**Comment by MaxedOut1** [comment] 2022-03-23 22:32
Any update on this? Its quite a valued fix and has been waited for for a while.

**Comment by MaxedOut1** [comment] 2022-04-02 13:22
Hey developers! I have found a possible fix for this bug! Please reply or message me and i will let u know. I have been able to get it to function on my server with an external plugin i made!

**Comment by UWUplus** [comment] 2022-06-23 20:08
> Hey developers! I have found a possible fix for this bug! Please reply or message me and i will let u know. I have been able to get it to function on my server with an external plugin i made!

Hi, none of the repo members, but I'm interested in this. If you would be able to provide this, feel free to message me on Discord: Ralf#7038

**Comment by pabloalba16** [comment] 2023-06-16 13:47
@MaxedOut1 Do you still have the plugin to bring back the animation?

**Comment by NotAlexNoyle** [comment] 2023-06-16 13:48
I am experiencing this issue on my server. Players on all 1.8 clients can't see people on newer clients drawing back their bows, and sometimes the player becomes invisible when they do so.

**Comment by FlorianMichael** [comment] 2024-04-03 11:30
Fixed in latest dev build.

**Closed by FlorianMichael** 2024-04-03 11:30 UTC
Labels: bug, help wanted
