### ISSUE TITLE
1.7 Client crashing

### ISSUE THREAD

**Issue by LoXR** [ViaVersion/ViaRewind#287] opened 2021-03-03 09:38 UTC
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?
https://paste.gg/p/anonymous/4ff781601fa24dc286dfea02b2d1b8db

**How can we reproduce it?**
Using Vanilla 1.7.10 Client and joining one of my hubs. I join, but sadly get hit with Internal Exception: java.io.IOException: An exisiting connection war forcibly cloded by the remote host.

**Expected behaviour**
Hopefully to have 1.7 players join with any issues.

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/5b72533e1447897a68f278c4193de6d95116283269c9f4064eb581bc700f6735

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Travertine

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by LoXR** [comment] 2021-03-09 07:11
Found out due to NametagEdit's "LongTags" option. Having to set that false sorted this issue out. of the long error, but another issue did arise but is known. Unsure if a fix will ever come along to sort the view-distance and somehow auto adjust for 1.7 clients?

**Comment by LoXR** [comment] 2021-03-09 07:20
And got two errors which may be common related: "The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte
Exit Code: -1" Possible due to View_distance being over 2?

And "The game crashed whilst unexpected errorError: java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'collideRule_8214'.Exit Code: -1" And possibly fixed due to NametagEdit's ClearEmptyTeamsInterval being -1, set it to 60.

**Comment by LoXR** [comment] 2021-03-11 09:03
Still attempting to figure out all the fixes for 1.7 clients. Sadly all that is left down to is citizens not working for 1.7 clients. The reason for the "The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte
Exit Code: -1" So will have to try figure it out through hopefully the settings in citizens.

**Comment by creeper123123321** [comment] 2021-06-19 23:08
duplicate of #275?

**Closed by creeper123123321** 2021-06-19 23:08 UTC
