### ISSUE TITLE
Error with wither bossbar with custom name

### ISSUE THREAD

**Issue by AlexProgrammerDE** [ViaVersion/ViaRewind#385] opened 2022-03-11 19:31 UTC
**Describe the bug, provide any errors**
When loading a wither with a custom name (nametaged), the plugin shows an error in the server console. This seems to be an issue with the bossbar conversion. https://paste.gg/p/anonymous/011bbfcc5b404c3986e34bb34c50f0e0
This extremely spams our console as we have quite a lot of withers on our server.

**How can we reproduce it?**
1. Login on 1.8.9
2. Spawn a wither with a custom name right next to you `/summon wither ~ ~ ~ {CustomName:"Custom Name Hello google.com/test",CustomNameVisible:1b}`
3. Console shows error.

**Expected behaviour**
No error in console.

**Screenshots**
It does show the custom name in the bossbar anyway. The error still happens.
![image](https://user-images.githubusercontent.com/40795980/157929908-bc11ebfd-e5f7-4bbd-822d-f23a7bddca0d.png)

**ViaVersion Dump:**
https://dump.viaversion.com/f364d00a77f35b7511ce0e3380b43c587d697224c85b8ec9c189e3ac28f7148a

**Additional server info**
We use Velocity. 
> AuthMeVelocity, BotSentry, CommandWhitelist, EpicGuard, Geyser-Velocity, log4jfix, LuckPerms, PistonMOTD, PistonQueue, ServerUtils, Triton, VelocityTools and VelocityPluginManager

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment] 2022-03-11 19:31
![Platform: git--Dionysus--%227629866%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%227629866%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 6 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.0): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by FlorianMichael** [comment] 2024-04-29 00:16
Can't reproduce with latest Via* plugins, tried a 1.9 server with a 1.8 client. This seems to get fixed by the adventure->MCStructs migration Via* plugins did a while ago, if you manage to still reproduce it with latest plugin versions, make a new issue or reopen this one.

**Closed by FlorianMichael** 2024-04-29 00:16 UTC
Labels: bug
