### ISSUE TITLE
ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF CHAT_MESSAGE (0x02)

### ISSUE THREAD

**Issue by TDSTOS** [ViaVersion/ViaRewind#408] opened 2022-08-25 18:51 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/0560775456c5b186ece6ddbb309a23b5c3ac72fb8f98e9b8806bccf007e0d945

### Console Error

https://paste.gg/p/anonymous/79989bcc1c894fca94b0fd5b3dc0965a

### Bug Description

The bug appears when a player with version 1.7.x joins

### Steps to Reproduce

1. Login with a 1.7.x client
2. Hit or do anything a normal player would do

### Expected Behavior

Dont know what to write here .-.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by HowardZHY** [comment] 2022-09-06 07:14
dump of
https://github.com/ViaVersion/ViaRewind/issues/362

**Comment by creeper123123321** [comment] 2022-09-07 10:23
duplicate of #362

**Closed by creeper123123321** 2022-09-07 10:23 UTC
Labels: Unconfirmed

**Comment by TDSTOS** [comment] 2022-09-07 11:08
> duplicate of #362

That was literally already said
