### ISSUE TITLE
placing a tnt sounds like placing a stone block.

### ISSUE THREAD

**Issue by rqyyy** [ViaVersion/ViaRewind#490] opened 2024-02-27 09:36 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/1c975c50b66db0525b9170dc87b3d492fdbc51c93f70145e428aead81d64b2ad

### Bug Description

when a player place tnt block, they hear different sound of placing a stone block. only players with lower version (1.8.9) are experieceing this. i already have via rewind legacy support.

### Steps to Reproduce

login with 1.8.9 or any older version to a 1.20.4 (latest) server and check sound by placing a "tnt"

### Expected Behavior

the block placing sound should be of "TNT"

### Additional Server Info

im running papermc 1.20.4 with these plugins 
![image](https://github.com/ViaVersion/ViaRewind/assets/105806586/3d56e3b6-fb29-4ccb-bffe-494cdce7a327)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment] 2024-02-27 09:36
![Platform: git--Paper--381%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--381%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w07a-SNAPSHOT): 4 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w07a--SNAPSHOT)-4%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w07a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w07a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by rqyyy** [comment] 2024-02-27 14:20
i tried updating to latest dev build, still the issue persists
new dump https://dump.viaversion.com/d1ace68d111d76f547ac90ac7fd51cf6aa0e6722f9830d370b61948f5c0171c8

**Comment by FlorianMichael** [comment] 2024-02-29 12:40
Block placement doesn't has sound at all (Tested on a 1.9 spigot server)

**Comment by FlorianMichael** [comment] 2024-04-03 11:35
Placing a tnt sounds normal with ViaRewind-Legacy-Support installed, will close this since I plan on moving the sound translation into ViaRewind and I can't reproduce your issue with the same setup.

**Closed by FlorianMichael** 2024-04-03 11:35 UTC
Labels: bug
